RUN apt-get update && apt-get install -y git locales locales-all
RUN pip install --upgrade pip

RUN mkdir -p /etc/nginx/conf.d/ssl/pems
ADD nginx_conf/ssl/pems/ /etc/nginx/conf.d/ssl/pems/
RUN chmod 644 /etc/nginx/conf.d/ssl/pems/*
RUN update-ca-certificates

ARG BRANCH
RUN git clone https://github.com/nsirolli/distribucion.git
RUN cd distribucion && git checkout ${BRANCH:-master} && cd ..

RUN cp distribucion/settings.py distribucion/distribucion/settings.py
RUN chmod +x distribucion/tools/create_db

RUN git clone https://github.com/nsirolli/allocation.git
RUN pip install -e allocation
RUN pip install -r allocation/requirements.txt

WORKDIR distribucion

RUN pip install -r requirements.txt
RUN python manage.py collectstatic --no-input
